In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[3, 2, 4],
                        [3, 6, 71],
                        [2, 76, 98]]])
TENSOR

tensor([[[ 3,  2,  4],
         [ 3,  6, 71],
         [ 2, 76, 98]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[ 3,  2,  4],
        [ 3,  6, 71],
        [ 2, 76, 98]])

### Random tensors



In [25]:
# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0882, 0.7783, 0.5006, 0.9506],
        [0.5818, 0.4820, 0.2852, 0.2028],
        [0.3308, 0.1839, 0.4302, 0.9664]])

In [27]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [3]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [12]:
# Use torch.arange()
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

#### Note 
- Right type of data
- Right shape
- Right device

In [22]:
# Float 32 tensor, default
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # Datatype
                               device="cuda", # Device to run on
                               requires_grad=False) # Store gradiant
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0'), torch.float32)

In [21]:
float_16_tensor = torch.tensor([5, 13.3, 5], dtype=torch.float16, device="cpu")
float_16_tensor

tensor([ 5.0000, 13.2969,  5.0000], dtype=torch.float16)

In [23]:
float_64_tensor = float_32_tensor.type(torch.double)
float_64_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float64)